---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: '{{ .Values.deployment.name }}'
  namespace: '{{ .Values.deployment.namespace }}'
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
          - name: '{{ .Values.deployment.name }}'
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          restartPolicy: '{{ .Values.deployment.restartPolicy }}'
