---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: batcher-rates-coinbase
  namespace: cce
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.podinfod: semver:0.*.*
spec:
  releaseName: batcher-rates-coinbase
  chart:
    git: https://github.com/cceshop/deployment.git
    ref: master
    path: charts/batcher-rates-coinbase
  values:
    image:
      repository: 'quay.io/cceshop/batcher-rates-coinbase'
      tag: '37dcb0c'
      pullPolicy: Always
    deployment:
      name: batcher-rates-coinbase
      namespace: cce
      restartPolicy: OnFailure
