---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: customer-check-cardid
  namespace: cce
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.customer-check-cardid: semver:0.*.*
spec:
  releaseName: customer-check-cardid
  chart:
    git: https://github.com/cceshop/deployment.git
    ref: master
    path: charts/customer-checks
  values:
    image:
      repository: 'quay.io/cceshop/customer-check-cardid'
      tag: '0.0.2'
      pullPolicy: Always
    deployment:
      name: customer-check-cardid
      namespace: cce
      restartPolicy: OnFailure
      replicas: 1
    network:
      pod:
        port:
          name: http
          number: 8080
          protocol: HTTP
      service:
        type: ClusterIP
        port:
          name: tcp
          number: 80
          protocol: TCP
