---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: batcher-rates-coinbase
  namespace: cce
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.batcher-rates-coinbase: semver:0.*.*
spec:
  releaseName: batcher-rates-coinbase
  chart:
    git: https://github.com/cceshop/deployment.git
    ref: master
    path: charts/batcher-rates-coinbase
  values:
    image:
      repository: 'quay.io/cceshop/batcher-rates-coinbase'
      tag: 'c357a3e'
      pullPolicy: Always
    deployment:
      name: batcher-rates-coinbase
      namespace: cce
      restartPolicy: OnFailure
